server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            #- Cookie=username,yuukin    需要两个参数，一个是 Cookie name ,一个是正则表达式。
            #- After=2023-01-04T14:06:21.338+08:00[Asia/Shanghai]         在这时间之后才会匹配成功
            #- Before=2024-01-04T14:06:21.338+08:00[Asia/Shanghai]        在这时间之前才会匹配成功
            #- Between=2023-01-04T14:06:21.338+08:00[Asia/Shanghai] ,2024-01-04T14:06:21.338+08:00[Asia/Shanghai]   在这时间段内才会成功

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka